name: Coverage Checking

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

- uses: devmasx/coverage-check-action@v1.2.0
  with:
    type: lcov
    result_path: report/coverage.lcov
    min_coverage: 70
    token: ${{ github.token }}